package com.saveetha.LeaveManagemnet.enums;

public enum DepartmentName {
    COMPUTER_SCIENCE,
    INFORMATION_TECHNOLOGY,
    ELECTRICAL_ENGINEERING,
    ELECTRONICS_COMMUNICATION,
    MECHANICAL_ENGINEERING,
    CIVIL_ENGINEERING,
    AERONAUTICAL_ENGINEERING,
    AUTOMOBILE_ENGINEERING,
    BIOTECHNOLOGY,
    CHEMICAL_ENGINEERING,
    INDUSTRIAL_ENGINEERING,
    MECHATRONICS_ENGINEERING,
    DATA_SCIENCE_ENGINEERING,
    ARTIFICIAL_INTELLIGENCE,
    ROBOTICS_ENGINEERING
}
